#include <iostream>
#include <chrono>
#include <csignal>
#include <atomic>
#include <mutex>
#include <fstream>
#include <string>
#include <sstream>
#include <map>
#include <limits>
#include <vector>
#include <queue>
#include <unordered_map>
#include <algorithm>
#include <functional>
#include <cstring>
#include <regex>
#include <thread>
#include <condition_variable>
#include <cstdint>
#include <stdio.h>

