// This file is included in GLSL and C++ sources

#define GEOMETRY_ATTR_PRIMARY_VISIBLE 0x01
#define GEOMETRY_ATTR_CAST_SHADOWS 0x02
#define GEOMETRY_ATTR_REFLECTION_VISIBLE 0x04
#define GEOMETRY_ATTR_EMITTER 0x08
#define GEOMETRY_ATTR_TRANSPARENT 0x10
#define GEOMETRY_ATTR_FOG 0x20
#define GEOMETRY_ATTR_COLLIDER 0x40
#define GEOMETRY_ATTR_CELESTIAL 0x80
