// This file is included in GLSL and C++ sources

// Attributes to use for geometry creation (multiple can be used together)
#define GEOMETRY_ATTR_PRIMARY_VISIBLE 0x01
#define GEOMETRY_ATTR_CAST_SHADOWS 0x02
#define GEOMETRY_ATTR_REFLECTION_VISIBLE 0x04
#define GEOMETRY_ATTR_COLLIDER 0x08
// Only one of the following can be used
#define GEOMETRY_ATTR_SOLID 0x10
#define GEOMETRY_ATTR_WATER 0x20
#define GEOMETRY_ATTR_FOG 0x40
#define GEOMETRY_ATTR_ATMOSPHERE 0x80

// Masks to use for ray-tracing calls
#define RAY_TRACE_MASK_PRIMARY			GEOMETRY_ATTR_PRIMARY_VISIBLE
#define RAY_TRACE_MASK_SHADOWS			GEOMETRY_ATTR_CAST_SHADOWS
#define RAY_TRACE_MASK_REFLECTION		GEOMETRY_ATTR_REFLECTION_VISIBLE
#define RAY_TRACE_MASK_IN_SPACE			GEOMETRY_ATTR_SOLID|GEOMETRY_ATTR_WATER|GEOMETRY_ATTR_FOG|GEOMETRY_ATTR_ATMOSPHERE
#define RAY_TRACE_MASK_IN_ATMOSPHERE	GEOMETRY_ATTR_SOLID|GEOMETRY_ATTR_WATER|GEOMETRY_ATTR_FOG
#define RAY_TRACE_MASK_IN_FOG			GEOMETRY_ATTR_SOLID|GEOMETRY_ATTR_WATER
#define RAY_TRACE_MASK_IN_WATER			GEOMETRY_ATTR_SOLID

